// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8Qrj77ZG4poNLRJe6a4tu6s8DCB07yaM',
    appId: '1:985907915358:web:c2ccbfd54c14a42c7762cf',
    messagingSenderId: '985907915358',
    projectId: 'matchup-c9f3c',
    authDomain: 'matchup-c9f3c.firebaseapp.com',
    storageBucket: 'matchup-c9f3c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6oQ_rG8qT24fSlomL2CpPg_oabg1ozqQ',
    appId: '1:985907915358:android:77ad1a816fc4b8fd7762cf',
    messagingSenderId: '985907915358',
    projectId: 'matchup-c9f3c',
    storageBucket: 'matchup-c9f3c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCayFWR-IY-4LKa-DQwC4WHHZbBFC8rdRA',
    appId: '1:985907915358:ios:bbff27e5880e4d1b7762cf',
    messagingSenderId: '985907915358',
    projectId: 'matchup-c9f3c',
    storageBucket: 'matchup-c9f3c.firebasestorage.app',
    iosBundleId: 'com.example.matchup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCayFWR-IY-4LKa-DQwC4WHHZbBFC8rdRA',
    appId: '1:985907915358:ios:bbff27e5880e4d1b7762cf',
    messagingSenderId: '985907915358',
    projectId: 'matchup-c9f3c',
    storageBucket: 'matchup-c9f3c.firebasestorage.app',
    iosBundleId: 'com.example.matchup',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8Qrj77ZG4poNLRJe6a4tu6s8DCB07yaM',
    appId: '1:985907915358:web:93b741ea971a6c4f7762cf',
    messagingSenderId: '985907915358',
    projectId: 'matchup-c9f3c',
    authDomain: 'matchup-c9f3c.firebaseapp.com',
    storageBucket: 'matchup-c9f3c.firebasestorage.app',
  );
}
