platform :ios, '15.0'

flutter_application_path = File.expand_path('..', __dir__)
require File.expand_path(File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb'), __FILE__)

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods(flutter_application_path)
end

post_install do |installer|
  flutter_post_install(installer)
end
